export const UPDATE_VIDEO = "MANUAL EM FOI ATUALIZADO";
export const DELETE_VIDEO = "MANUAL EM FOI DELETADO";
export const UPLOAD_VIDEO = "MANUAL EM VIDEO FOI ENVIADO";
export const UPDATE_PDF = "MANUAL EM PDF(VIEW) FOI ATUALIZADO";
export const DELETE_PDF = "MANUAL EM PDF(VIEW) FOI DELETADO";
export const UPLOAD_PDF = "MANUAL EM PDF(VIEW) FOI ENVIADO";


